// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyMnBbw6yGSlJv4A2zv-OjU7zyyYvv9nM',
    appId: '1:144958538979:web:aba6ca2067b1c6081d31d6',
    messagingSenderId: '144958538979',
    projectId: 'hm-nuts',
    authDomain: 'hm-nuts.firebaseapp.com',
    storageBucket: 'hm-nuts.firebasestorage.app',
    measurementId: 'G-EJE1XXEX4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl5JeoTl_I6ruw02vE9mJ5jFI-KJkdvfU',
    appId: '1:144958538979:android:cf89a97f675913fb1d31d6',
    messagingSenderId: '144958538979',
    projectId: 'hm-nuts',
    storageBucket: 'hm-nuts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQpRYD7nYEUefWM1t78kugX5S_eTofmH4',
    appId: '1:144958538979:ios:05a7c1b0a233a4ac1d31d6',
    messagingSenderId: '144958538979',
    projectId: 'hm-nuts',
    storageBucket: 'hm-nuts.firebasestorage.app',
    iosBundleId: 'com.cashewpro.cashewproErp',
  );
}
